linters:
  enable-all: true
  disable:
    - wrapcheck
    - exhaustruct
    - depguard
    # Deprecated:
    - golint
    - structcheck
    - ifshort
    - nosnakecase
    - maligned
    - scopelint
    - varcheck
    - interfacer
    - deadcode
    - exhaustivestruct

issues:
  exclude-rules:
    - path: awsutil
      text: aws.+ is a global variable
    - path: .*
      text: .*Logger is a global variable
    - path: ".*_test.go"
      text: Function 'Test.+' has too many statements
    - path: "util.go"
      text: Function 'GetInstance' has cyclomatic complexity 11
