linters:
  enable-all: true
  disable:
    - nonamedreturns
    - wrapcheck
    - gomnd
    - nestif
    - exhaustruct
    - exhaustivestruct
    - depguard

issues:
  exclude-rules:
    - path: awsutil
      text: aws.+ is a global variable
    - path: ec2ssh.go
      text: G204
    - path: ".*_test.go"
      text: Function 'Test.+' has too many statements
