version: "2"

linters:
  enable-all: true
  disable:
    # Not useful for this project
    - wrapcheck
    - exhaustruct
    - depguard
    - gochecknoglobals
    - mnd

issues:
  exclude-rules:
    - path: ".*_test.go"
      linters:
        - funlen
