version: "2"

linters:
  default: all
  disable:
    # Not useful for this project
    - wrapcheck
    - exhaustruct
    - depguard
    - gochecknoglobals
    - mnd
    # Legacy suppressions
    - cyclop
    - embeddedstructfieldcheck
    - err113
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - gocognit
    - goconst
    - gocritic
    - godot
    - gomoddirectives
    - gosec
    - inamedparam
    - intrange
    - ireturn
    - lll
    - modernize
    - nestif
    - nlreturn
    - noctx
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - revive
    - tagalign
    - testifylint
    - testpackage
    - unparam
    - varnamelen
    - whitespace
    - wsl
    - wsl_v5
