linters:
  enable-all: true
  disable:
    - wrapcheck
    - exhaustruct
    - depguard
    # Deprecated:
    - golint
    - structcheck
    - ifshort
    - nosnakecase
    - maligned
    - scopelint
    - varcheck
    - interfacer
    - deadcode
    - exhaustivestruct
    - perfsprint
    - gochecknoglobals

issues:
  exclude-rules:
    - path: ".*_test.go"
      text: Function 'Test.+' has too many statements
    - path: "util.go"
      text: calculated cyclomatic complexity for function GetInstance is 11
