version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: ./cmd/ec2ssh
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

homebrew_casks:
  - repository:
      owner: ivoronin
      name: homebrew-ivoronin
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: https://github.com/ivoronin/ec2ssh
    description: Simplify SSH connections to AWS EC2 instances
    license: GPL-3.0-only
    binaries:
      - ec2ssh
    hooks:
      post:
        install: |
          system_command "ln", args: ["-sf", "#{HOMEBREW_PREFIX}/bin/ec2ssh", "#{HOMEBREW_PREFIX}/bin/ec2scp"]
          system_command "ln", args: ["-sf", "#{HOMEBREW_PREFIX}/bin/ec2ssh", "#{HOMEBREW_PREFIX}/bin/ec2sftp"]
          system_command "ln", args: ["-sf", "#{HOMEBREW_PREFIX}/bin/ec2ssh", "#{HOMEBREW_PREFIX}/bin/ec2list"]
        uninstall: |
          system_command "rm", args: ["-f", "#{HOMEBREW_PREFIX}/bin/ec2scp"]
          system_command "rm", args: ["-f", "#{HOMEBREW_PREFIX}/bin/ec2sftp"]
          system_command "rm", args: ["-f", "#{HOMEBREW_PREFIX}/bin/ec2list"]

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
