version: '3'

tasks:
  lint:
    cmds:
      - golangci-lint run
  test:
    cmds:
      - go test ./...
  demo:
    dir: demo
    cmds:
      - vhs demo.vhs
    sources:
      - demo.vhs
    generates:
      - demo.webp