name: Test
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    uses: ivoronin/github-workflows/.github/workflows/test.yml@da9a532c23890a7b70f130239a0abc93a268cdbe # main
    with:
      language: go
